// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"

	"github.com/YiZou89/zero-tiktok/apps/follow/rpc/internal/logic"
	"github.com/YiZou89/zero-tiktok/apps/follow/rpc/internal/svc"
	"github.com/YiZou89/zero-tiktok/apps/follow/rpc/model"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	model.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServer) Action(ctx context.Context, in *model.ActionRequest) (*model.ActionResponse, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *FollowServer) GetFollowIds(ctx context.Context, in *model.GetFollowIdsRequest) (*model.GetFollowIdsResponse, error) {
	l := logic.NewGetFollowIdsLogic(ctx, s.svcCtx)
	return l.GetFollowIds(in)
}

func (s *FollowServer) GetFollowerIds(ctx context.Context, in *model.GetFollowerIdsRequest) (*model.GetFollowerIdsResponse, error) {
	l := logic.NewGetFollowerIdsLogic(ctx, s.svcCtx)
	return l.GetFollowerIds(in)
}

func (s *FollowServer) GetRelation(ctx context.Context, in *model.GetRelationRequest) (*model.GetRelationResponse, error) {
	l := logic.NewGetRelationLogic(ctx, s.svcCtx)
	return l.GetRelation(in)
}

func (s *FollowServer) Add(ctx context.Context, in *model.AddRequest) (*model.AddResponse, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *FollowServer) Del(ctx context.Context, in *model.DelRequest) (*model.DelResponse, error) {
	l := logic.NewDelLogic(ctx, s.svcCtx)
	return l.Del(in)
}

func (s *FollowServer) GetFollowCount(ctx context.Context, in *model.GetFollowCountRequest) (*model.GetFollowCountResponse, error) {
	l := logic.NewGetFollowCountLogic(ctx, s.svcCtx)
	return l.GetFollowCount(in)
}
