// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package server

import (
	"context"

	"github.com/YiZou89/zero-tiktok/apps/favorite/rpc/internal/logic"
	"github.com/YiZou89/zero-tiktok/apps/favorite/rpc/internal/svc"
	"github.com/YiZou89/zero-tiktok/apps/favorite/rpc/model"
)

type FavoriteServer struct {
	svcCtx *svc.ServiceContext
	model.UnimplementedFavoriteServer
}

func NewFavoriteServer(svcCtx *svc.ServiceContext) *FavoriteServer {
	return &FavoriteServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteServer) Action(ctx context.Context, in *model.ActionRequest) (*model.ActionResponse, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *FavoriteServer) AddAction(ctx context.Context, in *model.ActionRequest) (*model.ActionResponse, error) {
	l := logic.NewAddActionLogic(ctx, s.svcCtx)
	return l.AddAction(in)
}

func (s *FavoriteServer) DelAction(ctx context.Context, in *model.ActionRequest) (*model.ActionResponse, error) {
	l := logic.NewDelActionLogic(ctx, s.svcCtx)
	return l.DelAction(in)
}

func (s *FavoriteServer) GetVideoIds(ctx context.Context, in *model.GetVideoIdsRequest) (*model.GetVideoIdsResponse, error) {
	l := logic.NewGetVideoIdsLogic(ctx, s.svcCtx)
	return l.GetVideoIds(in)
}

func (s *FavoriteServer) GetFavoriteCount(ctx context.Context, in *model.GetFavoriteCountRequest) (*model.GetFavoriteCountResponse, error) {
	l := logic.NewGetFavoriteCountLogic(ctx, s.svcCtx)
	return l.GetFavoriteCount(in)
}

func (s *FavoriteServer) GetFavorite(ctx context.Context, in *model.GetFavoriteRequest) (*model.GetFavoriteResponse, error) {
	l := logic.NewGetFavoriteLogic(ctx, s.svcCtx)
	return l.GetFavorite(in)
}
