// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package server

import (
	"context"

	"github.com/YiZou89/zero-tiktok/apps/favorite/rpc/internal/logic"
	"github.com/YiZou89/zero-tiktok/apps/favorite/rpc/internal/svc"
	"github.com/YiZou89/zero-tiktok/apps/favorite/rpc/model"
)

type FavoriteServer struct {
	svcCtx *svc.ServiceContext
	model.UnimplementedFavoriteServer
}

func NewFavoriteServer(svcCtx *svc.ServiceContext) *FavoriteServer {
	return &FavoriteServer{
		svcCtx: svcCtx,
	}
}

// 添加点赞操作
func (s *FavoriteServer) Action(ctx context.Context, in *model.ActionRequest) (*model.ActionResponse, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

// 获取用户点赞的视频id
func (s *FavoriteServer) GetVideoIds(ctx context.Context, in *model.GetVideoIdsRequest) (*model.GetVideoIdsResponse, error) {
	l := logic.NewGetVideoIdsLogic(ctx, s.svcCtx)
	return l.GetVideoIds(in)
}

// 检查用户对视频是否点过赞
func (s *FavoriteServer) GetFavorite(ctx context.Context, in *model.GetFavoriteRequest) (*model.GetFavoriteResponse, error) {
	l := logic.NewGetFavoriteLogic(ctx, s.svcCtx)
	return l.GetFavorite(in)
}
