// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package follow

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/follow/rpc/model"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionRequest          = model.ActionRequest
	ActionResponse         = model.ActionResponse
	GetFollowIdsRequest    = model.GetFollowIdsRequest
	GetFollowIdsResponse   = model.GetFollowIdsResponse
	GetFollowListRequest   = model.GetFollowListRequest
	GetFollowListResponse  = model.GetFollowListResponse
	GetFollowerIdsRequest  = model.GetFollowerIdsRequest
	GetFollowerIdsResponse = model.GetFollowerIdsResponse
	GetRelationRequest     = model.GetRelationRequest
	GetRelationResponse    = model.GetRelationResponse
	Request                = model.Request
	Response               = model.Response

	Follow interface {
		// 关注操作
		Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
		// 获取粉丝列表
		GetFollowerIds(ctx context.Context, in *GetFollowerIdsRequest, opts ...grpc.CallOption) (*GetFollowerIdsResponse, error)
		// 获取关注者列表
		GetFollowIds(ctx context.Context, in *GetFollowIdsRequest, opts ...grpc.CallOption) (*GetFollowIdsResponse, error)
		// 获取关注者列表，并查看是否关注自己
		GetFollowList(ctx context.Context, in *GetFollowListRequest, opts ...grpc.CallOption) (*GetFollowListResponse, error)
		// 查询关系
		GetRelation(ctx context.Context, in *GetRelationRequest, opts ...grpc.CallOption) (*GetRelationResponse, error)
	}

	defaultFollow struct {
		cli zrpc.Client
	}
)

func NewFollow(cli zrpc.Client) Follow {
	return &defaultFollow{
		cli: cli,
	}
}

// 关注操作
func (m *defaultFollow) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	client := model.NewFollowClient(m.cli.Conn())
	return client.Action(ctx, in, opts...)
}

// 获取粉丝列表
func (m *defaultFollow) GetFollowerIds(ctx context.Context, in *GetFollowerIdsRequest, opts ...grpc.CallOption) (*GetFollowerIdsResponse, error) {
	client := model.NewFollowClient(m.cli.Conn())
	return client.GetFollowerIds(ctx, in, opts...)
}

// 获取关注者列表
func (m *defaultFollow) GetFollowIds(ctx context.Context, in *GetFollowIdsRequest, opts ...grpc.CallOption) (*GetFollowIdsResponse, error) {
	client := model.NewFollowClient(m.cli.Conn())
	return client.GetFollowIds(ctx, in, opts...)
}

// 获取关注者列表，并查看是否关注自己
func (m *defaultFollow) GetFollowList(ctx context.Context, in *GetFollowListRequest, opts ...grpc.CallOption) (*GetFollowListResponse, error) {
	client := model.NewFollowClient(m.cli.Conn())
	return client.GetFollowList(ctx, in, opts...)
}

// 查询关系
func (m *defaultFollow) GetRelation(ctx context.Context, in *GetRelationRequest, opts ...grpc.CallOption) (*GetRelationResponse, error) {
	client := model.NewFollowClient(m.cli.Conn())
	return client.GetRelation(ctx, in, opts...)
}
