// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package follow

import (
	"context"
	model2 "github.com/YiZou89/zero-tiktok/apps/follow/model"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionRequest          = model2.ActionRequest
	ActionResponse         = model2.ActionResponse
	AddRequest             = model2.AddRequest
	AddResponse            = model2.AddResponse
	DelRequest             = model2.DelRequest
	DelResponse            = model2.DelResponse
	GetFollowCountRequest  = model2.GetFollowCountRequest
	GetFollowCountResponse = model2.GetFollowCountResponse
	GetFollowIdsRequest    = model2.GetFollowIdsRequest
	GetFollowIdsResponse   = model2.GetFollowIdsResponse
	GetFollowerIdsRequest  = model2.GetFollowerIdsRequest
	GetFollowerIdsResponse = model2.GetFollowerIdsResponse
	GetRelationRequest     = model2.GetRelationRequest
	GetRelationResponse    = model2.GetRelationResponse
	Request                = model2.Request
	Response               = model2.Response

	Follow interface {
		Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
		GetFollowIds(ctx context.Context, in *GetFollowIdsRequest, opts ...grpc.CallOption) (*GetFollowIdsResponse, error)
		GetFollowerIds(ctx context.Context, in *GetFollowerIdsRequest, opts ...grpc.CallOption) (*GetFollowerIdsResponse, error)
		GetRelation(ctx context.Context, in *GetRelationRequest, opts ...grpc.CallOption) (*GetRelationResponse, error)
		Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
		Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
		GetFollowCount(ctx context.Context, in *GetFollowCountRequest, opts ...grpc.CallOption) (*GetFollowCountResponse, error)
	}

	defaultFollow struct {
		cli zrpc.Client
	}
)

func NewFollow(cli zrpc.Client) Follow {
	return &defaultFollow{
		cli: cli,
	}
}

func (m *defaultFollow) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	client := model2.NewFollowClient(m.cli.Conn())
	return client.Action(ctx, in, opts...)
}

func (m *defaultFollow) GetFollowIds(ctx context.Context, in *GetFollowIdsRequest, opts ...grpc.CallOption) (*GetFollowIdsResponse, error) {
	client := model2.NewFollowClient(m.cli.Conn())
	return client.GetFollowIds(ctx, in, opts...)
}

func (m *defaultFollow) GetFollowerIds(ctx context.Context, in *GetFollowerIdsRequest, opts ...grpc.CallOption) (*GetFollowerIdsResponse, error) {
	client := model2.NewFollowClient(m.cli.Conn())
	return client.GetFollowerIds(ctx, in, opts...)
}

func (m *defaultFollow) GetRelation(ctx context.Context, in *GetRelationRequest, opts ...grpc.CallOption) (*GetRelationResponse, error) {
	client := model2.NewFollowClient(m.cli.Conn())
	return client.GetRelation(ctx, in, opts...)
}

func (m *defaultFollow) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	client := model2.NewFollowClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}

func (m *defaultFollow) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	client := model2.NewFollowClient(m.cli.Conn())
	return client.Del(ctx, in, opts...)
}

func (m *defaultFollow) GetFollowCount(ctx context.Context, in *GetFollowCountRequest, opts ...grpc.CallOption) (*GetFollowCountResponse, error) {
	client := model2.NewFollowClient(m.cli.Conn())
	return client.GetFollowCount(ctx, in, opts...)
}
