// Code generated by goctl. DO NOT EDIT.
package types

type Douyin_feed_request struct {
}

type Douyin_feed_response struct {
}

type Douyin_publish_action_request struct {
}

type Douyin_publish_action_response struct {
}

type Douyin_publish_list_request struct {
}

type Douyin_publish_list_response struct {
}

type UserRegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"Password"`
}

type UserRegisterResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	UserId     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type Douyin_user_login_request struct {
}

type Douyin_user_login_response struct {
}

type Douyin_user_info_request struct {
}

type Douyin_user_info_response struct {
}

type Douyin_favorite_action_request struct {
}

type Douyin_favorite_action_response struct {
}

type Douyin_favorite_list_request struct {
}

type Douyin_favorite_list_response struct {
}

type Douyin_comment_action_request struct {
}

type Douyin_comment_action_response struct {
}

type Douyin_comment_list_request struct {
}

type Douyin_comment_list_response struct {
}

type Douyin_relation_follow_list_request struct {
}

type Douyin_relation_follow_list_response struct {
}

type Douyin_relation_follower_list_request struct {
}

type Douyin_relation_follower_list_response struct {
}

type Douyin_relation_friend_list_request struct {
}

type Douyin_relation_friend_list_response struct {
}

type Douyin_relation_action_request struct {
}

type Douyin_relation_action_response struct {
}

type Douyin_message_action_request struct {
}

type Douyin_message_action_response struct {
}

type Douyin_message_chat_request struct {
}

type Douyin_message_chat_response struct {
}
