// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"Password"`
}

type UserRegisterResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	UserId     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type UserLoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	UserId     int64  `json:"user_id"`
	Token      string `json:"token"`
}

type UserInfoRequest struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type UserInfoResponse struct {
	StatusCode int32  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
	UserInfo   User   `json:"user"`
}

type User struct {
	Id              int64  `json:"id"`   //用户ID
	Name            string `json:"name"` //用户名
	FollowCount     int64  `json:"follow_count"`
	FollowerCount   int64  `json:"follower_count"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  int64  `json:"total_favorited"`
	WorkCount       int64  `json:"work_count"`
	FavoriteCount   int64  `json:"favorite_count"`
}

type Douyin_feed_request struct {
}

type Douyin_feed_response struct {
}

type Douyin_publish_action_request struct {
}

type Douyin_publish_action_response struct {
}

type Douyin_publish_list_request struct {
}

type Douyin_publish_list_response struct {
}

type Douyin_favorite_action_request struct {
}

type Douyin_favorite_action_response struct {
}

type Douyin_favorite_list_request struct {
}

type Douyin_favorite_list_response struct {
}

type Douyin_comment_action_request struct {
}

type Douyin_comment_action_response struct {
}

type Douyin_comment_list_request struct {
}

type Douyin_comment_list_response struct {
}

type Douyin_relation_follow_list_request struct {
}

type Douyin_relation_follow_list_response struct {
}

type Douyin_relation_follower_list_request struct {
}

type Douyin_relation_follower_list_response struct {
}

type Douyin_relation_friend_list_request struct {
}

type Douyin_relation_friend_list_response struct {
}

type Douyin_relation_action_request struct {
}

type Douyin_relation_action_response struct {
}

type Douyin_message_action_request struct {
}

type Douyin_message_action_response struct {
}

type Douyin_message_chat_request struct {
}

type Douyin_message_chat_response struct {
}
