syntax = "proto3";

package favorite;
option go_package="./pb";



service Favorite {
  // 添加点赞操作
  rpc Action(action_request) returns(action_response);
  // 获取用户点赞的视频id
  rpc GetVideoIds(get_video_ids_request) returns (get_video_ids_response);
  // 检查用户对视频是否点过赞
  rpc GetFavorite(get_favorite_request) returns(get_favorite_response);
}

message action_request {
  int64 user_id = 1;
  int64 video_id = 2;
  int32 action_type = 3;
  int64 author_id = 4;
}

message action_response {
  int32 code = 1;
  string msg = 2;
}


message get_video_ids_request {
  int64 user_id = 1;
}

message get_video_ids_response {
  int64 video_num = 1;
  repeated int64 video_ids = 2;
}

message get_favorite_request {
  int64 user_id = 1;
  int64 video_id = 2;
}

message get_favorite_response {
  int64 action_type = 1;
}