// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followerFieldNames          = builder.RawFieldNames(&Follower{})
	followerRows                = strings.Join(followerFieldNames, ",")
	followerRowsExpectAutoSet   = strings.Join(stringx.Remove(followerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followerRowsWithPlaceHolder = strings.Join(stringx.Remove(followerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	followerModel interface {
		Insert(ctx context.Context, data *Follower) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Follower, error)
		Update(ctx context.Context, data *Follower) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFollowerModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Follower struct {
		Id         int64     `db:"id"`
		UserId     int64     `db:"user_id"`
		FollowerId int64     `db:"follower_id"`
		Cancel     bool      `db:"cancel"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newFollowerModel(conn sqlx.SqlConn) *defaultFollowerModel {
	return &defaultFollowerModel{
		conn:  conn,
		table: "`follower`",
	}
}

func (m *defaultFollowerModel) withSession(session sqlx.Session) *defaultFollowerModel {
	return &defaultFollowerModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`follower`",
	}
}

func (m *defaultFollowerModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFollowerModel) FindOne(ctx context.Context, id int64) (*Follower, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followerRows, m.table)
	var resp Follower
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowerModel) Insert(ctx context.Context, data *Follower) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, followerRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FollowerId, data.Cancel)
	return ret, err
}

func (m *defaultFollowerModel) Update(ctx context.Context, data *Follower) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followerRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FollowerId, data.Cancel, data.Id)
	return err
}

func (m *defaultFollowerModel) tableName() string {
	return m.table
}
