// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package follow

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/tiktok-relation/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFollowRequest        = pb.AddFollowRequest
	AddFollowResponse       = pb.AddFollowResponse
	DelFollowRequest        = pb.DelFollowRequest
	DelFollowResponse       = pb.DelFollowResponse
	GetFollowListRequest    = pb.GetFollowListRequest
	GetFollowListResponse   = pb.GetFollowListResponse
	GetFollowerListRequest  = pb.GetFollowerListRequest
	GetFollowerListResponse = pb.GetFollowerListResponse
	GetRelationRequest      = pb.GetRelationRequest
	GetRelationResponse     = pb.GetRelationResponse
	User                    = pb.User

	Follow interface {
		// http
		AddFollow(ctx context.Context, in *AddFollowRequest, opts ...grpc.CallOption) (*AddFollowResponse, error)
		DelFollow(ctx context.Context, in *DelFollowRequest, opts ...grpc.CallOption) (*DelFollowResponse, error)
		// 获取关注者列表
		GetFollowList(ctx context.Context, in *GetFollowListRequest, opts ...grpc.CallOption) (*GetFollowListResponse, error)
		GetFollowerList(ctx context.Context, in *GetFollowerListRequest, opts ...grpc.CallOption) (*GetFollowerListResponse, error)
		// grpc
		GetRelation(ctx context.Context, in *GetRelationRequest, opts ...grpc.CallOption) (*GetRelationResponse, error)
	}

	defaultFollow struct {
		cli zrpc.Client
	}
)

func NewFollow(cli zrpc.Client) Follow {
	return &defaultFollow{
		cli: cli,
	}
}

// http
func (m *defaultFollow) AddFollow(ctx context.Context, in *AddFollowRequest, opts ...grpc.CallOption) (*AddFollowResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.AddFollow(ctx, in, opts...)
}

func (m *defaultFollow) DelFollow(ctx context.Context, in *DelFollowRequest, opts ...grpc.CallOption) (*DelFollowResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.DelFollow(ctx, in, opts...)
}

// 获取关注者列表
func (m *defaultFollow) GetFollowList(ctx context.Context, in *GetFollowListRequest, opts ...grpc.CallOption) (*GetFollowListResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetFollowList(ctx, in, opts...)
}

func (m *defaultFollow) GetFollowerList(ctx context.Context, in *GetFollowerListRequest, opts ...grpc.CallOption) (*GetFollowerListResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetFollowerList(ctx, in, opts...)
}

// grpc
func (m *defaultFollow) GetRelation(ctx context.Context, in *GetRelationRequest, opts ...grpc.CallOption) (*GetRelationResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetRelation(ctx, in, opts...)
}
