// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package follow

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/tiktok-relation/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFollowRequest       = pb.AddFollowRequest
	AddFollowResponse      = pb.AddFollowResponse
	DelFollowRequest       = pb.DelFollowRequest
	DelFollowResponse      = pb.DelFollowResponse
	GetFollowIdsRequest    = pb.GetFollowIdsRequest
	GetFollowIdsResponse   = pb.GetFollowIdsResponse
	GetFollowListRequest   = pb.GetFollowListRequest
	GetFollowListResponse  = pb.GetFollowListResponse
	GetFollowerIdsRequest  = pb.GetFollowerIdsRequest
	GetFollowerIdsResponse = pb.GetFollowerIdsResponse
	GetRelationRequest     = pb.GetRelationRequest
	GetRelationResponse    = pb.GetRelationResponse

	Follow interface {
		// 关注操作
		AddFollow(ctx context.Context, in *AddFollowRequest, opts ...grpc.CallOption) (*AddFollowResponse, error)
		DelFollow(ctx context.Context, in *DelFollowRequest, opts ...grpc.CallOption) (*DelFollowResponse, error)
		// 查询关系
		GetRelation(ctx context.Context, in *GetRelationRequest, opts ...grpc.CallOption) (*GetRelationResponse, error)
		// 获取粉丝列表
		GetFollowerIds(ctx context.Context, in *GetFollowerIdsRequest, opts ...grpc.CallOption) (*GetFollowerIdsResponse, error)
		// 获取关注者列表
		GetFollowIds(ctx context.Context, in *GetFollowIdsRequest, opts ...grpc.CallOption) (*GetFollowIdsResponse, error)
		// 获取关注者列表
		GetFollowList(ctx context.Context, in *GetFollowListRequest, opts ...grpc.CallOption) (*GetFollowListResponse, error)
	}

	defaultFollow struct {
		cli zrpc.Client
	}
)

func NewFollow(cli zrpc.Client) Follow {
	return &defaultFollow{
		cli: cli,
	}
}

// 关注操作
func (m *defaultFollow) AddFollow(ctx context.Context, in *AddFollowRequest, opts ...grpc.CallOption) (*AddFollowResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.AddFollow(ctx, in, opts...)
}

func (m *defaultFollow) DelFollow(ctx context.Context, in *DelFollowRequest, opts ...grpc.CallOption) (*DelFollowResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.DelFollow(ctx, in, opts...)
}

// 查询关系
func (m *defaultFollow) GetRelation(ctx context.Context, in *GetRelationRequest, opts ...grpc.CallOption) (*GetRelationResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetRelation(ctx, in, opts...)
}

// 获取粉丝列表
func (m *defaultFollow) GetFollowerIds(ctx context.Context, in *GetFollowerIdsRequest, opts ...grpc.CallOption) (*GetFollowerIdsResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetFollowerIds(ctx, in, opts...)
}

// 获取关注者列表
func (m *defaultFollow) GetFollowIds(ctx context.Context, in *GetFollowIdsRequest, opts ...grpc.CallOption) (*GetFollowIdsResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetFollowIds(ctx, in, opts...)
}

// 获取关注者列表
func (m *defaultFollow) GetFollowList(ctx context.Context, in *GetFollowListRequest, opts ...grpc.CallOption) (*GetFollowListResponse, error) {
	client := pb.NewFollowClient(m.cli.Conn())
	return client.GetFollowList(ctx, in, opts...)
}
