// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package video

import (
	"context"

	"github.com/YiZou89/zero-tiktok/apps/video/rpc/model"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FeedRequest                 = model.FeedRequest
	FeedResponse                = model.FeedResponse
	GetFavorListRequest         = model.GetFavorListRequest
	GetFavorListResponse        = model.GetFavorListResponse
	GetListByAuthorIdRequest    = model.GetListByAuthorIdRequest
	GetListByAuthorIdResponse   = model.GetListByAuthorIdResponse
	GetListByUserIdRequest      = model.GetListByUserIdRequest
	GetListByUserIdResponse     = model.GetListByUserIdResponse
	GetPublishListRequest       = model.GetPublishListRequest
	GetPublishListResponse      = model.GetPublishListResponse
	GetVideoByIdRequest         = model.GetVideoByIdRequest
	GetVideoByIdResponse        = model.GetVideoByIdResponse
	GetVideosByIdsRequest       = model.GetVideosByIdsRequest
	GetVideosByIdsResponse      = model.GetVideosByIdsResponse
	PublishActionRequest        = model.PublishActionRequest
	PublishActionResponse       = model.PublishActionResponse
	UpdateFavoriteCountRequest  = model.UpdateFavoriteCountRequest
	UpdateFavoriteCountResponse = model.UpdateFavoriteCountResponse
	UserInfo                    = model.UserInfo
	VideoDetail                 = model.VideoDetail
	VideoInfo                   = model.VideoInfo

	Video interface {
		// 发布视频
		PublishAction(ctx context.Context, in *PublishActionRequest, opts ...grpc.CallOption) (*PublishActionResponse, error)
		// 点赞后更新视频计数
		UpdateFavoriteCount(ctx context.Context, in *UpdateFavoriteCountRequest, opts ...grpc.CallOption) (*UpdateFavoriteCountResponse, error)
		// 查询视频流
		Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
		// 根据用户id查询发布的所有视频信息，不需要再查询用户信息
		GetListByAuthorId(ctx context.Context, in *GetListByAuthorIdRequest, opts ...grpc.CallOption) (*GetListByAuthorIdResponse, error)
		// 根据用户id查询发布的所有视频信息，已经对应用户的点赞信息，不需要查询作者信息
		GetPublishList(ctx context.Context, in *GetPublishListRequest, opts ...grpc.CallOption) (*GetPublishListResponse, error)
		// 根据用户id，点赞的视频id，查询视频详细信息和作者信息
		GetFavorList(ctx context.Context, in *GetFavorListRequest, opts ...grpc.CallOption) (*GetFavorListResponse, error)
		// 根据视频id查询视频详细信息，不包括作者详细信息
		GetVideoById(ctx context.Context, in *GetVideoByIdRequest, opts ...grpc.CallOption) (*GetVideoByIdResponse, error)
		// 根据视频id查询视频详细信息，不包括作者详细信息
		GetVideosByIds(ctx context.Context, in *GetVideosByIdsRequest, opts ...grpc.CallOption) (*GetVideosByIdsResponse, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

// 发布视频
func (m *defaultVideo) PublishAction(ctx context.Context, in *PublishActionRequest, opts ...grpc.CallOption) (*PublishActionResponse, error) {
	client := model.NewVideoClient(m.cli.Conn())
	return client.PublishAction(ctx, in, opts...)
}

// 点赞后更新视频计数
func (m *defaultVideo) UpdateFavoriteCount(ctx context.Context, in *UpdateFavoriteCountRequest, opts ...grpc.CallOption) (*UpdateFavoriteCountResponse, error) {
	client := model.NewVideoClient(m.cli.Conn())
	return client.UpdateFavoriteCount(ctx, in, opts...)
}

// 查询视频流
func (m *defaultVideo) Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	client := model.NewVideoClient(m.cli.Conn())
	return client.Feed(ctx, in, opts...)
}

// 根据用户id查询发布的所有视频信息，不需要再查询用户信息
func (m *defaultVideo) GetListByAuthorId(ctx context.Context, in *GetListByAuthorIdRequest, opts ...grpc.CallOption) (*GetListByAuthorIdResponse, error) {
	client := model.NewVideoClient(m.cli.Conn())
	return client.GetListByAuthorId(ctx, in, opts...)
}

// 根据用户id查询发布的所有视频信息，已经对应用户的点赞信息，不需要查询作者信息
func (m *defaultVideo) GetPublishList(ctx context.Context, in *GetPublishListRequest, opts ...grpc.CallOption) (*GetPublishListResponse, error) {
	client := model.NewVideoClient(m.cli.Conn())
	return client.GetPublishList(ctx, in, opts...)
}

// 根据用户id，点赞的视频id，查询视频详细信息和作者信息
func (m *defaultVideo) GetFavorList(ctx context.Context, in *GetFavorListRequest, opts ...grpc.CallOption) (*GetFavorListResponse, error) {
	client := model.NewVideoClient(m.cli.Conn())
	return client.GetFavorList(ctx, in, opts...)
}

// 根据视频id查询视频详细信息，不包括作者详细信息
func (m *defaultVideo) GetVideoById(ctx context.Context, in *GetVideoByIdRequest, opts ...grpc.CallOption) (*GetVideoByIdResponse, error) {
	client := model.NewVideoClient(m.cli.Conn())
	return client.GetVideoById(ctx, in, opts...)
}

// 根据视频id查询视频详细信息，不包括作者详细信息
func (m *defaultVideo) GetVideosByIds(ctx context.Context, in *GetVideosByIdsRequest, opts ...grpc.CallOption) (*GetVideosByIdsResponse, error) {
	client := model.NewVideoClient(m.cli.Conn())
	return client.GetVideosByIds(ctx, in, opts...)
}
