// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package videoservice

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/tiktok-video/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FeedRequest           = pb.FeedRequest
	FeedResponse          = pb.FeedResponse
	GetVideosRequest      = pb.GetVideosRequest
	GetVideosResponse     = pb.GetVideosResponse
	PublishActionRequest  = pb.PublishActionRequest
	PublishActionResponse = pb.PublishActionResponse
	PublishListRequest    = pb.PublishListRequest
	PublishListResponse   = pb.PublishListResponse
	User                  = pb.User
	Video                 = pb.Video

	VideoService interface {
		Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
		PublishAction(ctx context.Context, in *PublishActionRequest, opts ...grpc.CallOption) (*PublishActionResponse, error)
		PublishList(ctx context.Context, in *PublishListRequest, opts ...grpc.CallOption) (*PublishListResponse, error)
		GetVideos(ctx context.Context, in *GetVideosRequest, opts ...grpc.CallOption) (*GetVideosResponse, error)
	}

	defaultVideoService struct {
		cli zrpc.Client
	}
)

func NewVideoService(cli zrpc.Client) VideoService {
	return &defaultVideoService{
		cli: cli,
	}
}

func (m *defaultVideoService) Feed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	client := pb.NewVideoServiceClient(m.cli.Conn())
	return client.Feed(ctx, in, opts...)
}

func (m *defaultVideoService) PublishAction(ctx context.Context, in *PublishActionRequest, opts ...grpc.CallOption) (*PublishActionResponse, error) {
	client := pb.NewVideoServiceClient(m.cli.Conn())
	return client.PublishAction(ctx, in, opts...)
}

func (m *defaultVideoService) PublishList(ctx context.Context, in *PublishListRequest, opts ...grpc.CallOption) (*PublishListResponse, error) {
	client := pb.NewVideoServiceClient(m.cli.Conn())
	return client.PublishList(ctx, in, opts...)
}

func (m *defaultVideoService) GetVideos(ctx context.Context, in *GetVideosRequest, opts ...grpc.CallOption) (*GetVideosResponse, error) {
	client := pb.NewVideoServiceClient(m.cli.Conn())
	return client.GetVideos(ctx, in, opts...)
}
