// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/tiktok-video/internal/logic"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-video/internal/svc"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-video/pb"
)

type VideoServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVideoServiceServer
}

func NewVideoServiceServer(svcCtx *svc.ServiceContext) *VideoServiceServer {
	return &VideoServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServiceServer) Feed(ctx context.Context, in *pb.FeedRequest) (*pb.FeedResponse, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}

func (s *VideoServiceServer) PublishAction(ctx context.Context, in *pb.PublishActionRequest) (*pb.PublishActionResponse, error) {
	l := logic.NewPublishActionLogic(ctx, s.svcCtx)
	return l.PublishAction(in)
}

func (s *VideoServiceServer) PublishList(ctx context.Context, in *pb.PublishListRequest) (*pb.PublishListResponse, error) {
	l := logic.NewPublishListLogic(ctx, s.svcCtx)
	return l.PublishList(in)
}

func (s *VideoServiceServer) GetVideos(ctx context.Context, in *pb.GetVideosRequest) (*pb.GetVideosResponse, error) {
	l := logic.NewGetVideosLogic(ctx, s.svcCtx)
	return l.GetVideos(in)
}
