// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/tiktok-relation/internal/logic"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-relation/internal/svc"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-relation/pb"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServer) AddFollow(ctx context.Context, in *pb.AddFollowRequest) (*pb.AddFollowResponse, error) {
	l := logic.NewAddFollowLogic(ctx, s.svcCtx)
	return l.AddFollow(in)
}

func (s *FollowServer) DelFollow(ctx context.Context, in *pb.DelFollowRequest) (*pb.DelFollowResponse, error) {
	l := logic.NewDelFollowLogic(ctx, s.svcCtx)
	return l.DelFollow(in)
}

func (s *FollowServer) GetFollowList(ctx context.Context, in *pb.GetFollowListRequest) (*pb.GetFollowListResponse, error) {
	l := logic.NewGetFollowListLogic(ctx, s.svcCtx)
	return l.GetFollowList(in)
}

func (s *FollowServer) GetFollowerList(ctx context.Context, in *pb.GetFollowerListRequest) (*pb.GetFollowerListResponse, error) {
	l := logic.NewGetFollowerListLogic(ctx, s.svcCtx)
	return l.GetFollowerList(in)
}

func (s *FollowServer) GetRelation(ctx context.Context, in *pb.GetRelationRequest) (*pb.GetRelationResponse, error) {
	l := logic.NewGetRelationLogic(ctx, s.svcCtx)
	return l.GetRelation(in)
}

func (s *FollowServer) MGetRelation(ctx context.Context, in *pb.MGetRelationRequest) (*pb.MGetRelationResponse, error) {
	l := logic.NewMGetRelationLogic(ctx, s.svcCtx)
	return l.MGetRelation(in)
}
