// Code generated by goctl. DO NOT EDIT.
// Source: follow.proto

package server

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/tiktok-relation/internal/logic"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-relation/internal/svc"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-relation/pb"
)

type FollowServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFollowServer
}

func NewFollowServer(svcCtx *svc.ServiceContext) *FollowServer {
	return &FollowServer{
		svcCtx: svcCtx,
	}
}

// 关注操作
func (s *FollowServer) AddFollow(ctx context.Context, in *pb.AddFollowRequest) (*pb.AddFollowResponse, error) {
	l := logic.NewAddFollowLogic(ctx, s.svcCtx)
	return l.AddFollow(in)
}

func (s *FollowServer) DelFollow(ctx context.Context, in *pb.DelFollowRequest) (*pb.DelFollowResponse, error) {
	l := logic.NewDelFollowLogic(ctx, s.svcCtx)
	return l.DelFollow(in)
}

// 查询关系
func (s *FollowServer) GetRelation(ctx context.Context, in *pb.GetRelationRequest) (*pb.GetRelationResponse, error) {
	l := logic.NewGetRelationLogic(ctx, s.svcCtx)
	return l.GetRelation(in)
}

// 获取粉丝列表
func (s *FollowServer) GetFollowerIds(ctx context.Context, in *pb.GetFollowerIdsRequest) (*pb.GetFollowerIdsResponse, error) {
	l := logic.NewGetFollowerIdsLogic(ctx, s.svcCtx)
	return l.GetFollowerIds(in)
}

// 获取关注者列表
func (s *FollowServer) GetFollowIds(ctx context.Context, in *pb.GetFollowIdsRequest) (*pb.GetFollowIdsResponse, error) {
	l := logic.NewGetFollowIdsLogic(ctx, s.svcCtx)
	return l.GetFollowIds(in)
}

// 获取关注者列表
func (s *FollowServer) GetFollowList(ctx context.Context, in *pb.GetFollowListRequest) (*pb.GetFollowListResponse, error) {
	l := logic.NewGetFollowListLogic(ctx, s.svcCtx)
	return l.GetFollowList(in)
}
