// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"github.com/YiZou89/zero-tiktok/apps/message/internal/logic"
	"github.com/YiZou89/zero-tiktok/apps/message/internal/svc"
	"github.com/YiZou89/zero-tiktok/apps/message/model"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	model.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) Action(ctx context.Context, in *model.ActionRequest) (*model.ActionResponse, error) {
	l := logic.NewActionLogic(ctx, s.svcCtx)
	return l.Action(in)
}

func (s *MessageServer) List(ctx context.Context, in *model.ListRequest) (*model.ListResponse, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}
