// Code generated by goctl. DO NOT EDIT.
package handler

import (
	comment2 "github.com/joeyz1729/zero-tiktok/apps/tiktok-api/internal/handler/comment"
	favorite2 "github.com/joeyz1729/zero-tiktok/apps/tiktok-api/internal/handler/favorite"
	message2 "github.com/joeyz1729/zero-tiktok/apps/tiktok-api/internal/handler/message"
	relation2 "github.com/joeyz1729/zero-tiktok/apps/tiktok-api/internal/handler/relation"
	user2 "github.com/joeyz1729/zero-tiktok/apps/tiktok-api/internal/handler/user"
	video2 "github.com/joeyz1729/zero-tiktok/apps/tiktok-api/internal/handler/video"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-api/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: video2.FeedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/publish/action",
				Handler: video2.PublishActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/publish/list",
				Handler: video2.PublishListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/douyin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user2.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user2.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/tiktok-user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user2.InfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/douyin/tiktok-user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: favorite2.FavoriteActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: favorite2.FavoriteListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/favorite"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: comment2.ActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: comment2.ListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/comment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: relation2.RelationActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follow/list",
				Handler: relation2.RelationFollowListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/follower/list",
				Handler: relation2.RelationFollowerListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/relation"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: message2.MessageActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chat",
				Handler: message2.MessageChatHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/message"),
	)
}
