// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	followedFieldNames          = builder.RawFieldNames(&Followed{})
	followedRows                = strings.Join(followedFieldNames, ",")
	followedRowsExpectAutoSet   = strings.Join(stringx.Remove(followedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	followedRowsWithPlaceHolder = strings.Join(stringx.Remove(followedFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	followedModel interface {
		Insert(ctx context.Context, data *Followed) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Followed, error)
		Update(ctx context.Context, data *Followed) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFollowedModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Followed struct {
		Id         int64     `db:"id"`
		UserId     int64     `db:"user_id"`
		FollowedId int64     `db:"followed_id"`
		Cancel     bool      `db:"cancel"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newFollowedModel(conn sqlx.SqlConn) *defaultFollowedModel {
	return &defaultFollowedModel{
		conn:  conn,
		table: "`followed`",
	}
}

func (m *defaultFollowedModel) withSession(session sqlx.Session) *defaultFollowedModel {
	return &defaultFollowedModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`followed`",
	}
}

func (m *defaultFollowedModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFollowedModel) FindOne(ctx context.Context, id int64) (*Followed, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", followedRows, m.table)
	var resp Followed
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFollowedModel) Insert(ctx context.Context, data *Followed) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, followedRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FollowedId, data.Cancel)
	return ret, err
}

func (m *defaultFollowedModel) Update(ctx context.Context, data *Followed) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, followedRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.FollowedId, data.Cancel, data.Id)
	return err
}

func (m *defaultFollowedModel) tableName() string {
	return m.table
}
