syntax = "proto3";

package user;
option go_package="./model";

service User {
  rpc UserInfo(user_info_request) returns(user_info_response);
  rpc Register(register_request) returns(register_response);
  rpc Login(login_request) returns(login_response);
  rpc GetIdByName(get_id_by_name_request) returns(get_id_by_name_response);
  rpc GetUserById(get_user_by_id_request) returns(get_user_by_id_response);
  rpc UpdateFollowInfo(update_follow_info_request) returns(update_follow_info_response);
  rpc UpdateFavoriteInfo(update_favorite_info_request) returns(update_favorite_info_response);
  rpc UpdateWorkInfo(update_work_info_request) returns(update_work_info_response);
}

message get_id_by_name_request  {
  string username = 1;
}

message get_id_by_name_response {
  bool exist = 1;
  int64 user_id = 2;
}


message user_info_request {
  int64 user_id = 1; // 用户id
  string token = 2; // 用户鉴权token
}

message user_info_response {
  int32 status_code = 1; // 状态码，0-成功，其他值-失败
  string status_msg = 2; // 返回状态描述
  UserInfo user = 3; // 用户信息
}

message register_request {
  string username = 1; // 注册用户名，最长32个字符
  string password = 2; // 密码，最长32个字符
}

message register_response {
  int64 user_id = 1; // 用户id
}

message login_request {
  string username = 1; // 登录用户名
  string password = 2; // 登录密码
}

message login_response {
  int64 user_id = 1;
}


message UserInfo {
  int64 id = 1; // 用户id
  string name = 2; // 用户名称
  int64 follow_count = 3; // 关注总数
  int64 follower_count = 4; // 粉丝总数
  bool is_follow = 5; // true-已关注，false-未关注
  string avatar = 6; //用户头像
  string background_image = 7; //用户个人页顶部大图
  string signature = 8; //个人简介
  int64 total_favorited = 9; //获赞数量
  int64 work_count = 10; //作品数量
  int64 favorite_count = 11; //点赞数量
}


message get_user_by_id_request {
  int64 user_id = 1;
}

message get_user_by_id_response {
  int64 id = 1;
  string name = 2;
  string avatar = 3;
  string background_image = 4;
  string signature = 5;
}

message update_follow_info_request {
  int64 user_id = 1;
  int64 to_user_id = 2;
  bool action_type = 3;
}

message update_follow_info_response {
  int32 status_code = 1;
  string status_msg = 2;
}



message update_favorite_info_request {
  int64 user_id = 1;
  int64 video_id = 2;
  bool action_type = 3;
}

message update_favorite_info_response {
  int32 status_code = 1;
  string status_msg = 2;
}

message update_work_info_request {
  int64 user_id = 1;
  int64 video_id = 2;
  int64 work_count= 3;
}

message update_work_info_response {
  int32 status_code = 1;
  string status_msg = 2;
}

