// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package favoriteclient

import (
	"context"

	"github.com/YiZou89/zero-tiktok/apps/favorite/favorite/favorite"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = favorite.Request
	Response = favorite.Response

	Favorite interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultFavorite struct {
		cli zrpc.Client
	}
)

func NewFavorite(cli zrpc.Client) Favorite {
	return &defaultFavorite{
		cli: cli,
	}
}

func (m *defaultFavorite) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := favorite.NewFavoriteClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
