syntax = "proto3";

package follow;
option go_package="./pb";

service Follow {
  rpc AddFollow(add_follow_request) returns(add_follow_response);
  rpc DelFollow(del_follow_request) returns(del_follow_response);

  rpc GetFollowList(get_follow_list_request) returns(get_follow_list_response);
  rpc GetFollowerList(get_follower_list_request) returns(get_follower_list_response);


  rpc GetRelation(get_relation_request) returns(get_relation_response);
  rpc MGetRelation(MGetRelationRequest) returns(MGetRelationResponse);
}


message add_follow_request {
  int64 user_id = 1;
  int64 to_user_id = 2;
}
message add_follow_response {
}

message del_follow_request {
  int64 user_id = 1;
  int64 to_user_id = 2;
}
message del_follow_response {
}

message get_follow_list_request {
  int64 user_id = 1;
  int64 to_user_id = 2;
}
message get_follow_list_response {
  repeated User list = 1;
}

message get_follower_list_request {
  int64 user_id = 1;
  int64 to_user_id = 2;
}
message get_follower_list_response {
  repeated User list = 1;
}

message get_relation_request {
  int64 user_id = 1;
  int64 to_user_id = 2;
}
message get_relation_response {
  bool is_following = 1;
  bool is_followed = 2;
}

message MGetRelationRequest {
  int64 user_id = 1;
  repeated int64 to_user_ids = 2;
}

message MGetRelationResponse {
  repeated bool is_following = 1;
  repeated bool is_followed = 2;
}

message User {
  int64 id = 1; // 用户id
  string name = 2; // 用户名称
  int64 follow_count = 3; // 关注总数
  int64 follower_count = 4; // 粉丝总数
  bool is_follow = 5; // true-已关注，false-未关注
  string avatar = 6; //用户头像
  string background_image = 7; //用户个人页顶部大图
  string signature = 8; //个人简介
  int64 total_favorited = 9; //获赞数量
  int64 work_count = 10; //作品数量
  int64 favorite_count = 11; //点赞数量
}