// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package message

import (
	"context"

	"github.com/YiZou89/zero-tiktok/apps/message/model"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActionRequest  = model.ActionRequest
	ActionResponse = model.ActionResponse

	Message interface {
		Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

func (m *defaultMessage) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	client := model.NewMessageClient(m.cli.Conn())
	return client.Action(ctx, in, opts...)
}
