// Code generated by goctl. DO NOT EDIT.
// Source: favorite.proto

package server

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/tiktok-favor/internal/logic"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-favor/internal/svc"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-favor/pb"
)

type FavoriteServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFavoriteServer
}

func NewFavoriteServer(svcCtx *svc.ServiceContext) *FavoriteServer {
	return &FavoriteServer{
		svcCtx: svcCtx,
	}
}

// 添加点赞操作
func (s *FavoriteServer) AddThumbup(ctx context.Context, in *pb.AddThumbupRequest) (*pb.AddThumbupResponse, error) {
	l := logic.NewAddThumbupLogic(ctx, s.svcCtx)
	return l.AddThumbup(in)
}

// 取消点赞
func (s *FavoriteServer) DeleteThumbup(ctx context.Context, in *pb.DeleteThumbupRequest) (*pb.DeleteThumbupResponse, error) {
	l := logic.NewDeleteThumbupLogic(ctx, s.svcCtx)
	return l.DeleteThumbup(in)
}

// 检查用户对视频是否点过赞
func (s *FavoriteServer) CheckThumbup(ctx context.Context, in *pb.CheckThumbupRequest) (*pb.CheckThumbupResponse, error) {
	l := logic.NewCheckThumbupLogic(ctx, s.svcCtx)
	return l.CheckThumbup(in)
}

// 获取用户点赞的视频id
func (s *FavoriteServer) GetThumbupVideoIds(ctx context.Context, in *pb.GetThumbupVideoIdsRequest) (*pb.GetThumbupVideoIdsResponse, error) {
	l := logic.NewGetThumbupVideoIdsLogic(ctx, s.svcCtx)
	return l.GetThumbupVideoIds(in)
}
