// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/tiktok-user/server/internal/logic"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-user/server/internal/svc"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-user/server/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// http api
func (s *UserServiceServer) Register(ctx context.Context, in *pb.RegisterRequest) (*pb.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 用户登陆
func (s *UserServiceServer) Login(ctx context.Context, in *pb.LoginRequest) (*pb.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 查询用户信息
func (s *UserServiceServer) UserInfo(ctx context.Context, in *pb.UserInfoRequest) (*pb.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

// rpc
func (s *UserServiceServer) UpdateFollowInfo(ctx context.Context, in *pb.UpdateFollowInfoRequest) (*pb.UpdateFollowInfoResponse, error) {
	l := logic.NewUpdateFollowInfoLogic(ctx, s.svcCtx)
	return l.UpdateFollowInfo(in)
}

// 点赞后更新用户计数
func (s *UserServiceServer) UpdateFavoriteInfo(ctx context.Context, in *pb.UpdateFavoriteInfoRequest) (*pb.UpdateFavoriteInfoResponse, error) {
	l := logic.NewUpdateFavoriteInfoLogic(ctx, s.svcCtx)
	return l.UpdateFavoriteInfo(in)
}

// 发布视频后更新用户计数
func (s *UserServiceServer) UpdateWorkInfo(ctx context.Context, in *pb.UpdateWorkInfoRequest) (*pb.UpdateWorkInfoResponse, error) {
	l := logic.NewUpdateWorkInfoLogic(ctx, s.svcCtx)
	return l.UpdateWorkInfo(in)
}

// 关注等操作检查用户id是否合法
func (s *UserServiceServer) GetUserById(ctx context.Context, in *pb.GetUserByIdRequest) (*pb.GetUserByIdResponse, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

// 根据id列表批量获取用户信息
func (s *UserServiceServer) GetUsers(ctx context.Context, in *pb.GetUsersRequest) (*pb.GetUsersResponse, error) {
	l := logic.NewGetUsersLogic(ctx, s.svcCtx)
	return l.GetUsers(in)
}

func (s *UserServiceServer) GetIdByName(ctx context.Context, in *pb.GetIdByNameRequest) (*pb.GetIdByNameResponse, error) {
	l := logic.NewGetIdByNameLogic(ctx, s.svcCtx)
	return l.GetIdByName(in)
}

func (s *UserServiceServer) GetAuthor(ctx context.Context, in *pb.GetAuthorRequest) (*pb.GetAuthorResponse, error) {
	l := logic.NewGetAuthorLogic(ctx, s.svcCtx)
	return l.GetAuthor(in)
}

func (s *UserServiceServer) GetAuthors(ctx context.Context, in *pb.GetAuthorsRequest) (*pb.GetAuthorsResponse, error) {
	l := logic.NewGetAuthorsLogic(ctx, s.svcCtx)
	return l.GetAuthors(in)
}

func (s *UserServiceServer) FollowPrepare(ctx context.Context, in *pb.FollowPrepareRequest) (*pb.FollowPrepareRequest, error) {
	l := logic.NewFollowPrepareLogic(ctx, s.svcCtx)
	return l.FollowPrepare(in)
}
