// Code generated by goctl. DO NOT EDIT.
// Source: comment.proto

package server

import (
	"context"

	"github.com/joeyz1729/zero-tiktok/apps/tiktok-comment/internal/logic"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-comment/internal/svc"
	"github.com/joeyz1729/zero-tiktok/apps/tiktok-comment/pb"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) CommentAction(ctx context.Context, in *pb.CommentActionRequest) (*pb.CommentActionResponse, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}

func (s *CommentServer) GetVideoCommentList(ctx context.Context, in *pb.GetVideoCommentListRequest) (*pb.GetVideoCommentListResponse, error) {
	l := logic.NewGetVideoCommentListLogic(ctx, s.svcCtx)
	return l.GetVideoCommentList(in)
}

// 添加评论，根据user，video，comment_text
func (s *CommentServer) AddComment(ctx context.Context, in *pb.AddCommentRequest) (*pb.AddCommentResponse, error) {
	l := logic.NewAddCommentLogic(ctx, s.svcCtx)
	return l.AddComment(in)
}

// 删除评论，根据user，video，comment
func (s *CommentServer) DelComment(ctx context.Context, in *pb.DelCommentRequest) (*pb.DelCommentResponse, error) {
	l := logic.NewDelCommentLogic(ctx, s.svcCtx)
	return l.DelComment(in)
}

// 查询视频的评论列表
func (s *CommentServer) GetCommentList(ctx context.Context, in *pb.GetCommentListRequest) (*pb.GetCommentListResponse, error) {
	l := logic.NewGetCommentListLogic(ctx, s.svcCtx)
	return l.GetCommentList(in)
}

// 查询单条记录
func (s *CommentServer) GetComment(ctx context.Context, in *pb.GetCommentRequest) (*pb.GetCommentResponse, error) {
	l := logic.NewGetCommentLogic(ctx, s.svcCtx)
	return l.GetComment(in)
}
