syntax = "proto3";

package message;
option go_package="./data";

message action_request {
  int64 user_id = 1;
  int64 to_user_id = 2;
  string content = 3;
}

message action_response {
  string msg = 1;
}

service Message {
  rpc Action(action_request) returns(action_response);
  rpc List(list_request) returns(list_response);
}

message list_request {
  int64 user_id = 1;
  int64 to_user_id = 2;
  string pre_msg_time = 3;
}

message list_response{
  int64 message_len = 1;
  repeated MessageInfo message_list = 2;
}

message MessageInfo {
  int64 id = 1;
  int64 to_user_id = 2;
  int64 from_user_id = 3;
  string content = 4;
  string create_time = 5;
}