// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"github.com/YiZou89/zero-tiktok/apps/user/rpc/model"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FollowPrepareRequest       = model.FollowPrepareRequest
	FollowPrepareResponse      = model.FollowPrepareResponse
	GetAuthorRequest           = model.GetAuthorRequest
	GetAuthorResponse          = model.GetAuthorResponse
	GetAuthorsRequest          = model.GetAuthorsRequest
	GetAuthorsResponse         = model.GetAuthorsResponse
	GetIdByNameRequest         = model.GetIdByNameRequest
	GetIdByNameResponse        = model.GetIdByNameResponse
	GetUserByIdRequest         = model.GetUserByIdRequest
	GetUserByIdResponse        = model.GetUserByIdResponse
	GetUsersRequest            = model.GetUsersRequest
	GetUsersResponse           = model.GetUsersResponse
	LoginRequest               = model.LoginRequest
	LoginResponse              = model.LoginResponse
	RegisterRequest            = model.RegisterRequest
	RegisterResponse           = model.RegisterResponse
	UpdateFavoriteInfoRequest  = model.UpdateFavoriteInfoRequest
	UpdateFavoriteInfoResponse = model.UpdateFavoriteInfoResponse
	UpdateFollowInfoRequest    = model.UpdateFollowInfoRequest
	UpdateFollowInfoResponse   = model.UpdateFollowInfoResponse
	UpdateWorkInfoRequest      = model.UpdateWorkInfoRequest
	UpdateWorkInfoResponse     = model.UpdateWorkInfoResponse
	UserInfo                   = model.UserInfo
	UserInfoRequest            = model.UserInfoRequest
	UserInfoResponse           = model.UserInfoResponse

	User interface {
		// 用户注册
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		// 用户登陆
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 查询用户信息
		UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		// 关注后更新用户计数
		UpdateFollowInfo(ctx context.Context, in *UpdateFollowInfoRequest, opts ...grpc.CallOption) (*UpdateFollowInfoResponse, error)
		// 点赞后更新用户计数
		UpdateFavoriteInfo(ctx context.Context, in *UpdateFavoriteInfoRequest, opts ...grpc.CallOption) (*UpdateFavoriteInfoResponse, error)
		// 发布视频后更新用户计数
		UpdateWorkInfo(ctx context.Context, in *UpdateWorkInfoRequest, opts ...grpc.CallOption) (*UpdateWorkInfoResponse, error)
		// 关注等操作检查用户id是否合法
		GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error)
		// 根据id列表批量获取用户信息
		GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
		GetIdByName(ctx context.Context, in *GetIdByNameRequest, opts ...grpc.CallOption) (*GetIdByNameResponse, error)
		GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*GetAuthorResponse, error)
		GetAuthors(ctx context.Context, in *GetAuthorsRequest, opts ...grpc.CallOption) (*GetAuthorsResponse, error)
		FollowPrepare(ctx context.Context, in *FollowPrepareRequest, opts ...grpc.CallOption) (*FollowPrepareRequest, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 用户注册
func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 用户登陆
func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 查询用户信息
func (m *defaultUser) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

// 关注后更新用户计数
func (m *defaultUser) UpdateFollowInfo(ctx context.Context, in *UpdateFollowInfoRequest, opts ...grpc.CallOption) (*UpdateFollowInfoResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.UpdateFollowInfo(ctx, in, opts...)
}

// 点赞后更新用户计数
func (m *defaultUser) UpdateFavoriteInfo(ctx context.Context, in *UpdateFavoriteInfoRequest, opts ...grpc.CallOption) (*UpdateFavoriteInfoResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.UpdateFavoriteInfo(ctx, in, opts...)
}

// 发布视频后更新用户计数
func (m *defaultUser) UpdateWorkInfo(ctx context.Context, in *UpdateWorkInfoRequest, opts ...grpc.CallOption) (*UpdateWorkInfoResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.UpdateWorkInfo(ctx, in, opts...)
}

// 关注等操作检查用户id是否合法
func (m *defaultUser) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...grpc.CallOption) (*GetUserByIdResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}

// 根据id列表批量获取用户信息
func (m *defaultUser) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.GetUsers(ctx, in, opts...)
}

func (m *defaultUser) GetIdByName(ctx context.Context, in *GetIdByNameRequest, opts ...grpc.CallOption) (*GetIdByNameResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.GetIdByName(ctx, in, opts...)
}

func (m *defaultUser) GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*GetAuthorResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.GetAuthor(ctx, in, opts...)
}

func (m *defaultUser) GetAuthors(ctx context.Context, in *GetAuthorsRequest, opts ...grpc.CallOption) (*GetAuthorsResponse, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.GetAuthors(ctx, in, opts...)
}

func (m *defaultUser) FollowPrepare(ctx context.Context, in *FollowPrepareRequest, opts ...grpc.CallOption) (*FollowPrepareRequest, error) {
	client := model.NewUserClient(m.cli.Conn())
	return client.FollowPrepare(ctx, in, opts...)
}
