// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/YiZou89/zero-tiktok/apps/user/rpc/internal/logic"
	"github.com/YiZou89/zero-tiktok/apps/user/rpc/internal/model"
	"github.com/YiZou89/zero-tiktok/apps/user/rpc/internal/svc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	model.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) UserInfo(ctx context.Context, in *model.UserInfoRequest) (*model.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *UserServer) Register(ctx context.Context, in *model.RegisterRequest) (*model.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *model.LoginRequest) (*model.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetIdByName(ctx context.Context, in *model.GetIdByNameRequest) (*model.GetIdByNameResponse, error) {
	l := logic.NewGetIdByNameLogic(ctx, s.svcCtx)
	return l.GetIdByName(in)
}

func (s *UserServer) GetUserById(ctx context.Context, in *model.GetUserByIdRequest) (*model.GetUserByIdResponse, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

func (s *UserServer) UpdateFollowInfo(ctx context.Context, in *model.UpdateFollowInfoRequest) (*model.UpdateFollowInfoResponse, error) {
	l := logic.NewUpdateFollowInfoLogic(ctx, s.svcCtx)
	return l.UpdateFollowInfo(in)
}

func (s *UserServer) UpdateFavoriteInfo(ctx context.Context, in *model.UpdateFavoriteInfoRequest) (*model.UpdateFavoriteInfoResponse, error) {
	l := logic.NewUpdateFavoriteInfoLogic(ctx, s.svcCtx)
	return l.UpdateFavoriteInfo(in)
}

func (s *UserServer) UpdateWorkInfo(ctx context.Context, in *model.UpdateWorkInfoRequest) (*model.UpdateWorkInfoResponse, error) {
	l := logic.NewUpdateWorkInfoLogic(ctx, s.svcCtx)
	return l.UpdateWorkInfo(in)
}
